const http=require('http'),fs=require('fs'),path=require('path'),{chromium}=require('playwright');

const root=path.resolve(__dirname,'..'),port=8880,types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.webmanifest':'application/manifest+json'};
let browser;
const server=http.createServer((req,res)=>{const clean=decodeURIComponent(req.url.split('?')[0]),file=path.join(root,clean==='/'?'index.html':clean);if(!file.startsWith(root)){res.writeHead(403).end();return}fs.readFile(file,(error,data)=>{if(error){res.writeHead(404).end();return}res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});res.end(data)})}).listen(port,'127.0.0.1');

(async()=>{
  browser=await chromium.launch({channel:'msedge',headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:810}}),errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`http://127.0.0.1:${port}/index.html?test=1`,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__GENESIS_DEBUG__);await page.evaluate(()=>window.__GENESIS_DEBUG__.start());
  const curve=await page.evaluate(()=>window.__GENESIS_DEBUG__.difficultyCurve()),expectedCounts=[4,5,6,6,7,8,8,10,12],expectedRanged=[1,1,2,2,3,3,3,5,6],expectedCaps=[10,12,14,18,22,26,32,40,48];
  if(JSON.stringify(curve.rooms.map(r=>r.enemies))!==JSON.stringify(expectedCounts)||JSON.stringify(curve.rooms.map(r=>r.ranged))!==JSON.stringify(expectedRanged)||JSON.stringify(curve.rooms.map(r=>r.bulletCap))!==JSON.stringify(expectedCaps))throw new Error(`declared room curve mismatch: ${JSON.stringify(curve.rooms)}`);
  const rooms=[];
  for(const config of curve.rooms){const actual=await page.evaluate(({floor,room})=>window.__GENESIS_DEBUG__.enterCombat(floor,room-1),config);const sorted=[...actual.roster].sort(),expected=[...config.roster].sort();if(JSON.stringify(sorted)!==JSON.stringify(expected)||actual.threats.length!==1||actual.threats[0]!==config.threat||actual.bulletCap!==config.bulletCap||actual.firstFire<config.firstShotMin-.001)throw new Error(`actual room curve mismatch: ${JSON.stringify({config,actual})}`);if(config.threat===0){await page.evaluate(()=>window.__GENESIS_DEBUG__.simulate(85));const opening=await page.evaluate(()=>window.__GENESIS_DEBUG__.threatState());if(opening.enemyBullets!==0)throw new Error(`first room fired before readable warmup: ${JSON.stringify(opening)}`)}const saturated=await page.evaluate(()=>{for(let i=0;i<100;i++)window.__GENESIS_DEBUG__.injectEnemyThreat();return window.__GENESIS_DEBUG__.threatState()});if(saturated.enemyBullets!==config.bulletCap)throw new Error(`room bullet cap failed: ${JSON.stringify({config,saturated})}`);rooms.push({floor:config.floor,room:config.room,enemies:actual.roster.length,ranged:config.ranged,cap:saturated.bulletCap,firstFire:+actual.firstFire.toFixed(3)})}
  const bosses=[];
  for(let floor=1;floor<=3;floor++){await page.evaluate(f=>{const d=window.__GENESIS_DEBUG__;d.loadFloor(f);d.enterType('boss')},floor);await page.waitForTimeout(1600);let threat=await page.evaluate(()=>window.__GENESIS_DEBUG__.threatState()),config=curve.bosses[(floor-1)*3];if(threat.enemyBullets!==0||threat.bulletCap!==config.bulletCap)throw new Error(`boss ${floor} opening readability failed: ${JSON.stringify(threat)}`);for(let phase=1;phase<=2;phase++){await page.evaluate(p=>window.__GENESIS_DEBUG__.setBossPhase(p),phase);threat=await page.evaluate(()=>window.__GENESIS_DEBUG__.threatState());config=curve.bosses[(floor-1)*3+phase];if(threat.enemyBullets!==0||threat.bulletCap!==config.bulletCap||threat.bossFire<config.windup-.08)throw new Error(`boss ${floor} phase ${phase+1} windup failed: ${JSON.stringify({config,threat})}`);const saturated=await page.evaluate(()=>{for(let i=0;i<100;i++)window.__GENESIS_DEBUG__.showcaseBossThreat();return window.__GENESIS_DEBUG__.threatState()});if(saturated.enemyBullets!==config.bulletCap)throw new Error(`boss ${floor} phase ${phase+1} cap failed: ${JSON.stringify({config,saturated})}`);bosses.push({floor,phase:phase+1,cap:saturated.bulletCap,windup:+threat.bossFire.toFixed(3)})}if(floor===1){await page.evaluate(()=>{const d=window.__GENESIS_DEBUG__;d.setBossPhase(1);d.setBossPhase(2);d.simulate(2000)});const summons=await page.evaluate(()=>window.__GENESIS_DEBUG__.threatState().summons);if(summons>2)throw new Error(`cherub summon cap failed: ${summons}`)}if(floor===3){await page.evaluate(()=>{const d=window.__GENESIS_DEBUG__;d.setBossPhase(0);d.setBossPhase(1);d.simulate(2000)});const summons=await page.evaluate(()=>window.__GENESIS_DEBUG__.threatState().summons);if(summons>3)throw new Error(`hexa summon cap failed: ${summons}`)}}
  const hit=await page.evaluate(()=>{const d=window.__GENESIS_DEBUG__;d.loadFloor(1);d.setInvuln(0);const before=d.snapshot().hp;d.damage();const after=d.snapshot().hp,feedback=d.feedbackState();d.damage();const blocked=d.snapshot().hp;d.renderNow();return{before,after,blocked,feedback}});if(hit.after!==hit.before-1||hit.blocked!==hit.after||hit.feedback.shake<=0||hit.feedback.shake>3.21||hit.feedback.flash<=0||hit.feedback.flash>.121)throw new Error(`comfortable damage feedback failed: ${JSON.stringify(hit)}`);await page.screenshot({path:path.join(root,'neon-genesis-hit-feedback.png')});const settled=await page.evaluate(()=>{const d=window.__GENESIS_DEBUG__;d.tick(8);return d.feedbackState()});if(settled.shake>.01||settled.flash>.01||errors.length)throw new Error(`hit feedback did not settle cleanly: ${JSON.stringify({settled,errors})}`);
  console.log(JSON.stringify({ok:true,rooms,bosses,hit,settled},null,2));await browser.close();server.close();
})().catch(async error=>{console.error(error.stack||error);await browser?.close().catch(()=>{});server.close();process.exitCode=1;setTimeout(()=>process.exit(1),50)});
