const http=require('http'),fs=require('fs'),path=require('path'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),port=8877,types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.webmanifest':'application/manifest+json','.png':'image/png'};
const server=http.createServer((req,res)=>{const clean=decodeURIComponent(req.url.split('?')[0]),file=path.join(root,clean==='/'?'index.html':clean);if(!file.startsWith(root)){res.writeHead(403).end();return}fs.readFile(file,(error,data)=>{if(error){res.writeHead(404).end();return}res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});res.end(data)})}).listen(port,'127.0.0.1');
(async()=>{
  const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:810}});
  const errors=[],missing=[];page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text())});page.on('pageerror',error=>errors.push(error.message));page.on('response',r=>{if(r.status()>=400)missing.push(`${r.status()} ${r.url()}`)});
  await page.goto(`http://127.0.0.1:${port}/index.html?test=1`,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__GENESIS_DEBUG__);
  if(!await page.locator('#start-screen.visible').isVisible())throw new Error('menu missing');
  await page.screenshot({path:path.join(root,'neon-genesis-menu.png')});
  await page.click('#start-btn');
  if(!await page.locator('#story-screen.visible').isVisible())throw new Error('story chain did not open');
  const audioProbe=await page.evaluate(()=>window.__GENESIS_DEBUG__.probeAudio());
  if(audioProbe.state!=='running'||!audioProbe.timer||audioProbe.notesDelta<1||audioProbe.gain<.7||audioProbe.offlineRms<.015||audioProbe.offlinePeak<.04||audioProbe.offlinePeak>=.9)throw new Error(`audible music graph failed: ${JSON.stringify(audioProbe)}`);
  if(audioProbe.timeDelta>.05&&(audioProbe.rms<.02||audioProbe.peak<.04||audioProbe.peak>=.9))throw new Error(`live music signal outside range: ${JSON.stringify(audioProbe)}`);
  if(!(await page.locator('#music-btn').textContent()).includes('100%'))throw new Error('music button does not report active output');
  const shotProfiles=await page.evaluate(()=>window.__GENESIS_DEBUG__.probeShotProfiles()),shotProfileValues=Object.values(shotProfiles);
  if(shotProfileValues.length!==4||new Set(shotProfileValues.map(v=>v.duration)).size!==4||new Set(shotProfileValues.map(v=>v.signature)).size!==4||shotProfileValues.some(v=>v.peak<.15||v.peak>.7||v.rms<.04||v.rms>.2))throw new Error(`four-form cached shot audio failed: ${JSON.stringify(shotProfiles)}`);
  const storyTitles=[await page.locator('#story-title').textContent()],transitionNames=[await page.locator('#story-scene').evaluate(el=>getComputedStyle(el).animationName)];
  for(let i=0;i<8;i++){
    await page.click('#story-next');
    transitionNames.push(await page.locator('#story-scene').evaluate(el=>getComputedStyle(el).animationName));
    await page.waitForTimeout(520);
    storyTitles.push(await page.locator('#story-title').textContent());
    if(i===0){
      const resourceNames=[];
      for(const id of ['data','key','charge']){await page.locator(`#weapon-schematic [data-resource="${id}"]`).hover();await page.waitForTimeout(90);resourceNames.push((await page.locator('#weapon-name').textContent()).trim())}
      if(new Set(resourceNames).size!==3)throw new Error('interactive resource guide failed');
      await page.locator('#weapon-schematic [data-resource="key"]').hover();
      await page.screenshot({path:path.join(root,'neon-genesis-story-economy.png')});
    }
    if(i===2)await page.screenshot({path:path.join(root,'neon-genesis-story-weapon.png')});
    if(i===5){
      const roomCards=page.locator('#room-guide [data-room-guide]');
      if(await roomCards.count()!==8||!await roomCards.first().isVisible())throw new Error('eight room protocol cards missing');
      const roomNames=[];
      for(const id of ['start','combat','treasure','shop','secret','boss','vault','sanctum']){
        await page.locator(`[data-room-guide="${id}"]`).hover();await page.waitForTimeout(75);
        roomNames.push((await page.locator('#weapon-name').textContent()).trim());
        if(await page.locator('#room-guide [aria-selected="true"]').count()!==1)throw new Error(`room selection state failed: ${id}`);
      }
      if(new Set(roomNames).size!==8)throw new Error('room protocol details are not distinct');
      const secretCard=page.locator('[data-room-guide="secret"]');await secretCard.focus();
      if(!(await page.locator('#weapon-desc').textContent()).includes('爆破电荷'))throw new Error('secret room detail missing breach rule');
      const titleBefore=await page.locator('#story-title').textContent();await page.keyboard.press('Space');
      if(await page.locator('#story-title').textContent()!==titleBefore)throw new Error('room card Space advanced story');
      await page.keyboard.press('ArrowRight');
      if((await page.locator('#weapon-name').textContent()).trim()!=='执政官门')throw new Error('room card arrow navigation failed');
      await secretCard.hover();await page.waitForTimeout(120);
      await page.screenshot({path:path.join(root,'neon-genesis-story-rooms.png')});
    }
    if(i===6){
      if(await page.locator('#room-guide').isVisible())throw new Error('room guide leaked into boss onboarding');
      if(await page.locator('#room-guide [tabindex="0"]').count())throw new Error('hidden room guide remains tabbable');
      await page.screenshot({path:path.join(root,'neon-genesis-story-boss-guide.png')});
    }
  }
  if(new Set(storyTitles).size!==9)throw new Error('story chapters are not distinct');
  if(new Set(transitionNames).size!==9)throw new Error(`story transitions are not distinct: ${transitionNames.join(',')}`);
  if((await page.locator('#story-count').textContent()).trim()!=='09 / 09')throw new Error('story count is not nine');
  await page.click('#story-next');let snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());if(snap.mode!=='playing'||snap.floor!==1||snap.room!=='start'||!snap.musicEnabled)throw new Error('story-to-run transition failed');
  const readBattery=()=>page.evaluate(()=>{const meter=document.querySelector('#hearts'),cells=[...meter.children],after=getComputedStyle(meter,'::after');return{cells:cells.length,charged:cells.filter(cell=>cell.classList.contains('charged')).length,empty:cells.filter(cell=>cell.classList.contains('empty')).length,value:document.querySelector('#health-value')?.textContent.trim(),status:document.querySelector('#health-status')?.textContent.trim(),now:Number(meter.getAttribute('aria-valuenow')),max:Number(meter.getAttribute('aria-valuemax')),low:meter.classList.contains('low'),terminal:after.content!=='none'&&after.width!=='0px',animation:getComputedStyle(meter).animationName}});let battery=await readBattery();if(battery.cells!==6||battery.charged!==6||battery.empty!==0||battery.value!=='06 / 06'||battery.now!==6||battery.max!==6||!battery.terminal)throw new Error(`full battery HUD failed: ${JSON.stringify(battery)}`);await page.evaluate(()=>{const d=window.__GENESIS_DEBUG__;d.setResources({hp:2,maxHp:6});d.tick(1)});battery=await readBattery();if(battery.cells!==6||battery.charged!==2||battery.empty!==4||battery.value!=='02 / 06'||battery.status!=='LOW POWER'||!battery.low||battery.animation!=='none')throw new Error(`low battery HUD failed: ${JSON.stringify(battery)}`);await page.screenshot({path:path.join(root,'neon-genesis-battery-hud.png')});await page.evaluate(()=>{const d=window.__GENESIS_DEBUG__;d.setResources({hp:8,maxHp:8});d.tick(1)});battery=await readBattery();if(battery.cells!==8||battery.charged!==8||battery.value!=='08 / 08'||battery.max!==8||battery.low)throw new Error(`expanded battery HUD failed: ${JSON.stringify(battery)}`);await page.evaluate(()=>{const d=window.__GENESIS_DEBUG__;d.setResources({hp:6,maxHp:6});d.tick(1)});
  await page.evaluate(()=>{const d=window.__GENESIS_DEBUG__;d.setResources({hp:6,maxHp:6,shield:2});d.setInvuln(0);d.damage();d.tick(1)});battery=await readBattery();if(battery.charged!==6||battery.cells!==6)throw new Error(`shield incorrectly drained battery HUD: ${JSON.stringify(battery)}`);await page.evaluate(()=>{const d=window.__GENESIS_DEBUG__;d.setResources({hp:6,maxHp:6,shield:0});d.setInvuln(0);d.damage();d.tick(1)});battery=await readBattery();if(battery.charged!==5||battery.empty!==1||battery.value!=='05 / 06')throw new Error(`real damage did not drain one battery cell: ${JSON.stringify(battery)}`);await page.evaluate(()=>{const d=window.__GENESIS_DEBUG__;d.setResources({hp:6,maxHp:6,shield:0});d.setInvuln(1);d.tick(1)});
  const difficulty=await page.evaluate(()=>window.__GENESIS_DEBUG__.difficultyCurve()),roomCounts=difficulty.rooms.map(r=>r.enemies),rangedCounts=difficulty.rooms.map(r=>r.ranged),roomCaps=difficulty.rooms.map(r=>r.bulletCap),bossPressures=difficulty.bosses.map(b=>b.pressure);if(JSON.stringify(roomCounts)!==JSON.stringify([4,5,6,6,7,8,8,10,12,11,12,13,12,13,14,13,14,15])||JSON.stringify(rangedCounts)!==JSON.stringify([1,1,2,2,3,3,3,5,6,5,6,6,6,7,7,7,7,8])||JSON.stringify(roomCaps)!==JSON.stringify([10,12,14,18,22,26,32,40,48,52,58,64,66,70,76,78,82,88]))throw new Error(`difficulty room curve failed: ${JSON.stringify(difficulty.rooms)}`);if(!difficulty.rooms.every((r,i,a)=>!i||r.hpScale>a[i-1].hpScale)||difficulty.rooms[0].firstShotMin<1.55||difficulty.rooms[0].shooter.count!==1||JSON.stringify(bossPressures)!==JSON.stringify([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])||difficulty.bosses.some(b=>b.windup<.72))throw new Error(`difficulty coefficient progression failed: ${JSON.stringify(difficulty)}`);
  await page.evaluate(()=>window.__GENESIS_DEBUG__.simulate(30));await page.evaluate(()=>window.__GENESIS_DEBUG__.setPlayer(1175,385));await page.keyboard.down('KeyD');await page.evaluate(()=>window.__GENESIS_DEBUG__.simulate(3));await page.keyboard.up('KeyD');snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());if(snap.room!=='combat'||snap.x>260||Math.abs(snap.y-385)>45)throw new Error(`logical room entry position failed: ${JSON.stringify(snap)}`);
  await page.evaluate(()=>window.__GENESIS_DEBUG__.simulate(75));snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());const openingThreat=await page.evaluate(()=>window.__GENESIS_DEBUG__.threatState());if(snap.enemies!==4||snap.enemyBullets!==0||openingThreat.bulletCap!==10)throw new Error(`first combat warmup failed: ${JSON.stringify({snap,openingThreat})}`);
  const canvasBox=await page.locator('#game').boundingBox();await page.mouse.move(canvasBox.x+4,canvasBox.y+canvasBox.height/2);const tearsBeforeHover=snap.tears;await page.evaluate(()=>window.__GENESIS_DEBUG__.simulate(2));snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());if(snap.aimX>-.7||snap.tears!==tearsBeforeHover)throw new Error('mouse hover facing failed');
  await page.click('#music-btn');await page.waitForTimeout(140);snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());if(snap.musicEnabled||snap.musicTimerActive||snap.musicGainValue>=.02)throw new Error('music toggle off failed');
  await page.click('#music-btn');await page.waitForTimeout(140);snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());if(!snap.musicEnabled||snap.audioState!=='running'||!snap.musicTimerActive||snap.musicGainValue<.7)throw new Error('music toggle on failed');
  const suspendedShotAudio=await page.evaluate(()=>window.__GENESIS_DEBUG__.probeSuspendedShotAudio());if(!suspendedShotAudio.available||suspendedShotAudio.createdWhileSuspended!==0||suspendedShotAudio.voiceGrowth!==0||suspendedShotAudio.resumeRequests!==1||suspendedShotAudio.timeMoved>.001||!suspendedShotAudio.resumed||suspendedShotAudio.state!=='running')throw new Error(`suspended shot audio leaked nodes: ${JSON.stringify(suspendedShotAudio)}`);
  if(!await page.evaluate(()=>window.__GENESIS_DEBUG__.probeFastPickup()))throw new Error('high-speed swept pickup failed');
  const pickupPursuit=await page.evaluate(()=>window.__GENESIS_DEBUG__.probePickupPursuit());if(!pickupPursuit.allCaught||!pickupPursuit.fast||!pickupPursuit.frameStable)throw new Error(`accelerated pickup pursuit failed: ${JSON.stringify(pickupPursuit)}`);
  let shotSoundCount=(await page.evaluate(()=>window.__GENESIS_DEBUG__.shotAudioState())).played;
  for(const form of ['vanguard','wraith','beast','seraph']){await page.waitForTimeout(320);await page.evaluate(f=>window.__GENESIS_DEBUG__.switchForm(f),form);await page.evaluate(()=>window.__GENESIS_DEBUG__.clearWeaponFx());await page.evaluate(()=>window.__GENESIS_DEBUG__.fire(1,0));snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.tick(2));const shotAudio=await page.evaluate(()=>window.__GENESIS_DEBUG__.shotAudioState());if(snap.form!==form||!snap.tearForms.includes(form)||snap.muzzleFx<1||snap.muzzleFx>96)throw new Error(`form weapon FX failed: ${form}`);if(!shotAudio.ready||shotAudio.played<=shotSoundCount||shotAudio.voices>5)throw new Error(`form shot sound failed: ${form} ${JSON.stringify(shotAudio)}`);shotSoundCount=shotAudio.played;if(form==='beast'||form==='seraph'){await page.evaluate(()=>window.__GENESIS_DEBUG__.renderNow());await page.screenshot({path:path.join(root,`neon-genesis-weapon-${form}.png`)})}}
  await page.evaluate(()=>window.__GENESIS_DEBUG__.simulate(20));await page.keyboard.down('Shift');await page.keyboard.press('ArrowRight');await page.keyboard.up('Shift');snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());if(snap.form!=='wraith')throw new Error('physical form shortcut failed');
  await page.evaluate(()=>window.__GENESIS_DEBUG__.simulate(20));await page.keyboard.press('Digit3');snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());if(snap.form!=='beast')throw new Error('top-row number form shortcut failed');
  await page.evaluate(()=>window.__GENESIS_DEBUG__.simulate(20));await page.keyboard.press('Numpad4');snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());if(snap.form!=='seraph')throw new Error('numpad form shortcut failed');
  await page.evaluate(()=>window.__GENESIS_DEBUG__.simulate(20));await page.keyboard.press('Numpad2');snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());if(snap.form!=='wraith')throw new Error('numpad form restore failed');
  await page.evaluate(()=>window.__GENESIS_DEBUG__.enterType('combat'));await page.evaluate(()=>window.__GENESIS_DEBUG__.simulate(30));snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());
  if(snap.wallGroups<2||snap.obstacles<8||!snap.wallAligned)throw new Error('extended aligned terrain walls missing');
  const ricochetProbe=await page.evaluate(()=>window.__GENESIS_DEBUG__.probePlayerRicochet());if(!Object.values(ricochetProbe).every(Boolean))throw new Error(`player ricochet collision failed: ${JSON.stringify(ricochetProbe)}`);
  snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.showcaseRicochet());if(snap.ricochetFx<1||!snap.tearRicochets.some(t=>t.count>=1))throw new Error('ricochet visual feedback missing');await page.evaluate(()=>window.__GENESIS_DEBUG__.renderNow());await page.screenshot({path:path.join(root,'neon-genesis-ricochet.png')});await page.evaluate(()=>window.__GENESIS_DEBUG__.clearWeaponFx());
  await page.evaluate(()=>window.__GENESIS_DEBUG__.injectEnemyThreat());await page.evaluate(()=>window.__GENESIS_DEBUG__.fire(1,0));snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.tick(2));if(snap.enemySourceBullets<1||!snap.tearForms.includes('wraith'))throw new Error('player and enemy projectile classification failed');
  await page.evaluate(()=>window.__GENESIS_DEBUG__.renderNow());await page.screenshot({path:path.join(root,'neon-genesis-projectile-classes.png')});if(!await page.evaluate(()=>window.__GENESIS_DEBUG__.probeBulletWall()))throw new Error('enemy bullet crossed an obstacle');
  await page.evaluate(()=>window.__GENESIS_DEBUG__.hitFirstEnemy(3.6,false));snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.hitFirstEnemy(3.6,true));if(snap.damageTexts.length<2||snap.damageTexts.some(text=>text.includes('.')))throw new Error('integer damage feedback failed');snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.spawnPickup('coin',3));if(snap.pickupFx<1||snap.pickups<1)throw new Error('pickup highlight state missing');await page.evaluate(()=>window.__GENESIS_DEBUG__.renderNow());await page.screenshot({path:path.join(root,'neon-genesis-terrain-feedback.png')});
  for(const type of ['combat','treasure','shop','secret']){
    await page.evaluate(t=>window.__GENESIS_DEBUG__.enterType(t),type);
    snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());
    if(snap.room!==type)throw new Error(`room failed: ${type}`);
    if(type==='combat'){
      if(snap.enemies<4)throw new Error('combat enemies missing');
      await page.keyboard.down('ArrowRight');await page.evaluate(()=>window.__GENESIS_DEBUG__.simulate(12));await page.keyboard.up('ArrowRight');
      snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());if(snap.tears<1)throw new Error('directional shooting failed');
      const bombs=snap.bombs;await page.keyboard.press('KeyE');snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());if(snap.bombs!==bombs-1||snap.bombEntities!==1)throw new Error('bomb deployment failed');
      await page.evaluate(()=>window.__GENESIS_DEBUG__.renderNow());await page.screenshot({path:path.join(root,'neon-genesis-combat.png')});
      await page.evaluate(()=>window.__GENESIS_DEBUG__.setCrit(1));snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.autoplay(45));await page.evaluate(()=>window.__GENESIS_DEBUG__.renderNow());await page.screenshot({path:path.join(root,'neon-genesis-critical.png')});
      snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.autoplay());if(snap.enemies!==0||snap.roomsCleared<1||snap.critHits<1)throw new Error('real combat or critical hit failed');await page.evaluate(()=>window.__GENESIS_DEBUG__.setCrit(null));
    }
    if(type==='treasure'){
      await page.evaluate(()=>window.__GENESIS_DEBUG__.takePedestal(0));snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());if(snap.items.length+Object.keys(snap.upgrades).length<1)throw new Error('treasure choice failed');
      await page.evaluate(()=>{window.__GENESIS_DEBUG__.setPlayer(1130,365);window.__GENESIS_DEBUG__.setResources({bombs:1})});await page.keyboard.press('KeyE');await page.evaluate(()=>window.__GENESIS_DEBUG__.simulate(70));snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());if(!snap.secretRevealed)throw new Error('secret wall reveal failed');
    }
    if(type==='shop'){
      const beforePedestals=snap.pedestals;await page.evaluate(()=>{const d=window.__GENESIS_DEBUG__;d.setResources({coins:99});d.takePedestal(0)});snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());if(snap.coins>=99||snap.pedestals>=beforePedestals)throw new Error('shop purchase failed');
    }
  }
  await page.evaluate(()=>window.__GENESIS_DEBUG__.enterType('boss'));await page.waitForTimeout(1700);snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());if(snap.boss!=='cherub'||snap.bossPhase!==0)throw new Error('boss spawn failed');
  await page.evaluate(()=>window.__GENESIS_DEBUG__.renderNow());await page.waitForTimeout(300);await page.screenshot({path:path.join(root,'neon-genesis-boss.png')});
  const synergyItems=['prism','phase','volatile','tesla','drone','echo'];for(const item of synergyItems)await page.evaluate(id=>window.__GENESIS_DEBUG__.giveItem(id),item);snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());if(!synergyItems.every(id=>snap.items.includes(id)))throw new Error('item synergy setup failed');
  for(const phase of [1,2]){await page.evaluate(p=>window.__GENESIS_DEBUG__.setBossPhase(p),phase);snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());const phaseThreat=await page.evaluate(()=>window.__GENESIS_DEBUG__.threatState());if(snap.bossPhase!==phase||phaseThreat.enemyBullets!==0||phaseThreat.bossFire<.7)throw new Error(`boss phase ${phase} windup failed: ${JSON.stringify(phaseThreat)}`)}
  snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.showcaseBossThreat());if(snap.enemyBullets<1||snap.bossBullets<1||snap.hazards<1)throw new Error('boss threat setup or projectile classification failed');await page.evaluate(()=>window.__GENESIS_DEBUG__.renderNow());await page.screenshot({path:path.join(root,'neon-genesis-boss-projectiles.png')});snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.autoplay());if(snap.boss!==null||snap.enemies!==0||snap.enemyBullets!==0||snap.hazards!==0)throw new Error('real boss combat or death cleanup failed');
  await page.evaluate(()=>window.__GENESIS_DEBUG__.takePortal());snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());if(snap.floor!==2||snap.room!=='start')throw new Error('floor progression failed');
  const invulnProbe=await page.evaluate(()=>{const d=window.__GENESIS_DEBUG__;d.setInvuln(0);const before=d.snapshot().hp+d.snapshot().shield;d.damage();const first=d.snapshot(),feedback=d.feedbackState();d.damage();const immediate=d.snapshot(),immediateFeedback=d.feedbackState();d.tick(59);const settledFeedback=d.feedbackState();d.damage();const early=d.snapshot();d.tick(2);d.damage();const late=d.snapshot();return{before,first,feedback,immediate,immediateFeedback,settledFeedback,early,late}});if(invulnProbe.first.hp+invulnProbe.first.shield!==invulnProbe.before-1||invulnProbe.first.invuln<.99)throw new Error('initial damage or one-second invulnerability failed');if(invulnProbe.feedback.shake<=0||invulnProbe.feedback.shake>3.21||invulnProbe.feedback.flash<=0||invulnProbe.feedback.flash>.121||invulnProbe.immediateFeedback.shake!==invulnProbe.feedback.shake||invulnProbe.settledFeedback.shake>.01||invulnProbe.settledFeedback.flash>.01)throw new Error(`comfortable hit feedback failed: ${JSON.stringify(invulnProbe)}`);if(invulnProbe.immediate.hp+invulnProbe.immediate.shield!==invulnProbe.before-1||invulnProbe.early.hp+invulnProbe.early.shield!==invulnProbe.before-1)throw new Error('damage was not blocked during invulnerability');if(invulnProbe.late.hp+invulnProbe.late.shield!==invulnProbe.before-2)throw new Error('damage did not resume after one second');snap=invulnProbe.late;
  const bossIds=['cherub','matriarch','hexa','cherub','matriarch','hexa'];
  for(let floor=2;floor<=6;floor++){await page.evaluate(()=>{const d=window.__GENESIS_DEBUG__;d.enterType('boss');d.spawnBossNow()});snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());if(snap.floor!==floor||snap.boss!==bossIds[floor-1])throw new Error(`floor ${floor} boss failed: ${JSON.stringify(snap)}`);for(const phase of [1,2]){await page.evaluate(p=>window.__GENESIS_DEBUG__.setBossPhase(p),phase);snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());if(snap.bossPhase!==phase)throw new Error(`floor ${floor} boss phase ${phase} failed`)}await page.evaluate(()=>{const d=window.__GENESIS_DEBUG__;d.killBoss();d.takePortal()});snap=await page.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());if(floor<6&&(snap.floor!==floor+1||snap.room!=='start'))throw new Error(`floor ${floor+1} progression failed: ${JSON.stringify(snap)}`)}
  if(snap.mode!=='gameover'||!snap.victory)throw new Error('six-floor final victory failed');
  const portrait=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
  await portrait.goto(`http://127.0.0.1:${port}/index.html?test=1`,{waitUntil:'domcontentloaded'});await portrait.waitForFunction(()=>window.__GENESIS_DEBUG__);await portrait.waitForTimeout(160);let mobileLayout=await portrait.evaluate(()=>window.__GENESIS_DEBUG__.mobileLayout());const rotateButtonBox=await portrait.locator('#rotate-fullscreen-btn').boundingBox();if(mobileLayout.orientation!=='portrait'||!mobileLayout.rotate.visible||mobileLayout.shell.width<389||mobileLayout.shell.height<843||!mobileLayout.fullscreenButton.visible||mobileLayout.fullscreenButton.width<44||!rotateButtonBox||rotateButtonBox.height<44)throw new Error(`portrait rotation gate failed: ${JSON.stringify(mobileLayout)}`);await portrait.screenshot({path:path.join(root,'neon-genesis-portrait-rotate.png')});
  await portrait.setViewportSize({width:480,height:270});await portrait.waitForTimeout(180);mobileLayout=await portrait.evaluate(()=>window.__GENESIS_DEBUG__.mobileLayout());if(mobileLayout.orientation!=='landscape'||mobileLayout.rotate.visible||mobileLayout.shell.width>481||mobileLayout.shell.height>271||mobileLayout.fullscreenButton.right>481||mobileLayout.fullscreenButton.bottom>271)throw new Error(`compact landscape adaptation failed: ${JSON.stringify(mobileLayout)}`);await portrait.click('#start-btn');await portrait.waitForTimeout(120);for(let slide=0;slide<2;slide++){const nextBox=await portrait.locator('#story-next').boundingBox();if(!nextBox||nextBox.height<44||nextBox.y<0||nextBox.y+nextBox.height>271)throw new Error(`compact story action clipped on slide ${slide}: ${JSON.stringify(nextBox)}`);if(slide===0)await portrait.click('#story-next')}await portrait.screenshot({path:path.join(root,'neon-genesis-story-compact-mobile.png')});await portrait.close();
  const mobile=await browser.newPage({viewport:{width:844,height:390},hasTouch:true,isMobile:true});
  await mobile.goto(`http://127.0.0.1:${port}/index.html?test=1`,{waitUntil:'domcontentloaded'});await mobile.waitForFunction(()=>window.__GENESIS_DEBUG__);mobileLayout=await mobile.evaluate(()=>window.__GENESIS_DEBUG__.mobileLayout());if(!mobileLayout.fullscreenSupported||!mobileLayout.fullscreenButton.visible||mobileLayout.fullscreenButton.width<44||mobileLayout.rotate.visible)throw new Error(`landscape fullscreen control failed: ${JSON.stringify(mobileLayout)}`);await mobile.click('#start-btn');await mobile.click('#story-next');await mobile.waitForTimeout(420);
  await mobile.locator('#weapon-schematic [data-resource="charge"]').click();await mobile.waitForTimeout(340);await mobile.screenshot({path:path.join(root,'neon-genesis-story-economy-mobile.png')});
  await mobile.click('#story-next');await mobile.click('#story-next');await mobile.waitForTimeout(520);await mobile.screenshot({path:path.join(root,'neon-genesis-story-mobile.png')});
  for(let i=0;i<3;i++)await mobile.click('#story-next');await mobile.waitForTimeout(520);
  const mobileBossCard=mobile.locator('[data-room-guide="boss"]');await mobileBossCard.click();await mobile.waitForTimeout(140);
  if((await mobile.locator('#weapon-name').textContent()).trim()!=='执政官门')throw new Error('mobile room guide tap failed');
  const mobileRoomBox=await mobileBossCard.boundingBox();if(!mobileRoomBox||mobileRoomBox.height<44)throw new Error('mobile room card touch target too small');
  await mobile.screenshot({path:path.join(root,'neon-genesis-story-rooms-mobile.png')});
  await mobile.click('#story-skip');if(await mobile.locator('#touch-controls').evaluate(el=>getComputedStyle(el).display)==='none')throw new Error('touch controls missing');mobileLayout=await mobile.evaluate(()=>window.__GENESIS_DEBUG__.mobileLayout());if(!mobileLayout.moveStick.visible||!mobileLayout.shootStick.visible||mobileLayout.moveStick.width<70||mobileLayout.shootStick.width<70||mobileLayout.moveStick.x<mobileLayout.shell.x-1||mobileLayout.shootStick.right>mobileLayout.shell.right+1)throw new Error(`safe-area touch controls failed: ${JSON.stringify(mobileLayout)}`);await mobile.evaluate(()=>window.__GENESIS_DEBUG__.renderNow());await mobile.screenshot({path:path.join(root,'neon-genesis-mobile.png')});await mobile.close();
  const filePage=await browser.newPage({viewport:{width:1280,height:720}}),fileErrors=[];filePage.on('pageerror',error=>fileErrors.push(error.message));const fileUrl=`file:///${path.join(root,'index.html').replace(/\\/g,'/')}?test=1`;await filePage.goto(fileUrl,{waitUntil:'domcontentloaded'});await filePage.waitForFunction(()=>window.__GENESIS_DEBUG__);await filePage.click('#start-btn');
  const fileAudio=await filePage.evaluate(()=>window.__GENESIS_DEBUG__.probeAudio());if(fileAudio.state!=='running'||!fileAudio.timer||fileAudio.offlineRms<.015||fileAudio.offlinePeak<.04)throw new Error(`file-mode audio failed: ${JSON.stringify(fileAudio)}`);if(fileAudio.timeDelta>.05&&(fileAudio.rms<.02||fileAudio.peak<.04))throw new Error(`file-mode live audio signal failed: ${JSON.stringify(fileAudio)}`);
  for(let i=0;i<9;i++)await filePage.click('#story-next');const fileSnap=await filePage.evaluate(()=>window.__GENESIS_DEBUG__.snapshot());if(fileSnap.mode!=='playing'||fileSnap.floor!==1||fileSnap.room!=='start'||fileErrors.length)throw new Error(`file-mode launch failed: ${fileErrors.join(' | ')}`);await filePage.close();
  const meaningfulMissing=missing.filter(x=>!x.includes('favicon.ico'));if(errors.length||meaningfulMissing.length)throw new Error(`browser errors: ${errors.join(' | ')}; missing: ${meaningfulMissing.join(', ')}`);
  console.log(JSON.stringify({ok:true,snapshot:snap,checked:['nine-scene story chain','interactive three-resource guide','interactive eight-room protocol guide','room guide mouse keyboard and touch controls','room and boss onboarding','nine distinct story transitions','weapon story card','segmented battery health HUD','shield-safe health cells','top-row and numpad form shortcuts','audible compressed music graph','http and file audio unlock','high-speed swept pickup','four-form weapon FX','one-to-two player projectile ricochets','continuous player projectile wall collision','player enemy and boss projectile classes','extended direction-aligned terrain walls','enemy bullets blocked by walls','integer enlarged damage feedback','highlighted pickup spawn','logical room entry position','mouse-hover facing without firing','music mute resume and retry state','physical four-form controls','directional shooting','bomb deployment','critical hit feedback','real combat clear','free treasure and shop rooms','treasure pickup','secret wall reveal','shop purchase','six-item synergy','boss death bullet cleanup','real boss combat','all six bosses and eighteen phases','six-floor progression','one-second damage invulnerability','final victory','mobile controls','file-mode launch']},null,2));await browser.close();server.close();
})().catch(async error=>{console.error(error.stack||error);server.close();process.exitCode=1;setTimeout(()=>process.exit(1),50)});
